# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Enfnfnq's Blog
tagline:          '개발자의 기술 블로그'
description:      '개발과 관련된 다양한 내용을 공유하는 기술 블로그입니다.'
url:              https://Enfnfnq.github.io
baseurl:          /

author:
  name:           'Enfnfnq'
  url:            https://github.com/Enfnfnq

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Enfnfnq/Enfnfnq.github.io
